# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - name: repository
    value: 'euni.Admin'
  - name: dockerfile
    value: '$(Build.SourcesDirectory)/AdminBackend/eUni.services.admin/Dockerfile'
  - name: containerRegistry
    value: 'euniacr'

steps:
- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    repository: $(imageRepository)
    dockerfile: $(dockerfilePath)
    containerRegistry: 'euni-acr-connection'
    tags: |
      $(tag)